### ISSUE TITLE
Failed getting invoice

### ISSUE THREAD

**Issue by dtonon** [sudonym-btc/zap#1]
Great tool :)
For this LN address I got an error, ex:

```
  dtonon@ln.tips
  ✓ Got address information
  ✕ Failed getting invoice
    wrong description_hash (expected 71a9e9ec9f49a5c4c47cc13723da92c6e45326b30d27d0fa35373a6a407d1aa8, got 2c3057a6bcd61ec5c4eecd0cf89ebcfca13dd6320f6ab865483fddbe1458aaae)

```

Any idea?

**Comment by bumi** [comment]
btw the description hash check for LNURL should be dropped: https://github.com/lnurl/luds/pull/234

**Comment by pats2sats** [comment]
https://github.com/sudonym-btc/zap/releases/tag/v0.0.4

Fixed in new release.
